### ISSUE TITLE
Annotation processors must be explicitly declared now.

### ISSUE THREAD

**Issue by U-Ra-All** [faruktoptas/news-mvp#2]
When using the Android plugin 3.0.0, you must add annotation processors to the processor classpath using the annotationProcessor dependency configuration, as shown below:

dependencies {
    ...
    annotationProcessor 'com.google.dagger:dagger-compiler:<version-number>'
}

https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration?utm_source=android-studio#annotationProcessor_config

**Comment by faruktoptas** [comment]
Fixed after gradle update.
