### ISSUE TITLE
Facing an issue in auto generating debug apk from my branch 

### ISSUE THREAD

**Issue by ghost** [faruktoptas/news-mvp#3]
Hi Faruk ,
 I  have gone through your artical on medium.
i.e. https://medium.com/android-bits/android-app-from-scratch-part-5-continuous-integration-with-travis-ci-1a6d30d22822

you have explain very nicely about CI/CD
 now i am facing an issue   in   travis.yml script
i am not be able to generate debug apk in my branch / release section in github
after successful build in travis-ci
 at bottom its shows warning message
-----------------------------------------------
BUILD SUCCESSFUL in 5m 20s
26 actionable tasks: 26 executed
The command "./gradlew assembleDebug" exited with 0.
Skipping a deployment with the releases provider because this is not a tagged commit

----------------------------------------------
 Below is is my .travis.yml script 
 can you help me out  in this 
Thanks in Advance.
  
//------------------------------------------------------------------------------------------
language: android
jdk: oraclejdk8

#sudo: false

android:
  components:
    - platform-tools
    - tools

    - build-tools-28.0.3

    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew assembleDebug

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT

  on:
    
    branch: spike_1.3.1
    tags: true

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs

**Comment by faruktoptas** [comment]
Hi @rizwanonekosmos  `tags: true` means that you have to tag your commit before pushing it. If your commit is tagged deploy will start.
